import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./Components/Header";
import SessionWrapper from "./SessionWrapper";

export const metadata = {
  title: "Ecommerece",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <SessionWrapper>
        <body className="relative ">
          <Header />
          <main className="main-content justify-center items-center flex flex-col mx-auto">
            {children}
          </main>
        </body>
      </SessionWrapper>
    </html>
  );
}
